<?php

namespace CCDNForum\ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{
	

	/**
	 *
	 * @access public
	 * @param int $status_code
	 */	
	public function findForUserById($userId)
	{

		$query = $this->getEntityManager()
			->createQuery('
				SELECT s, t, fp, lp, b, c FROM CCDNForumForumBundle:Subscription s 
				LEFT JOIN s.topic t
				LEFT JOIN t.last_post lp
				LEFT JOIN lp.created_by lpu
				LEFT JOIN t.first_post fp
				LEFT JOIN fp.created_by fpu
				LEFT JOIN t.board b
				LEFT JOIN b.category c
				WHERE s.owned_by = :userId AND s.subscribed = true 
				GROUP BY t.id
				ORDER BY t.id ASC')
			->setParameter('userId', $userId);
		
		try {
			return new Pagerfanta(new DoctrineORMAdapter($query));
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
	


	/**
	 *
	 * @access public
	 * @param int $topicId, int $userId
	 */
	public function findTopicSubscriptionByTopicAndUserId($topicId, $userId)
	{
		$query = $this->getEntityManager()
			->createQuery('
				SELECT s, t FROM CCDNForumForumBundle:Subscription s
				LEFT JOIN s.topic t
				WHERE t.id = :topicId AND s.owned_by = :userId')
			->setParameters(array('topicId' => $topicId, 'userId' => $userId));
					
		try {
	        return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
	
}