
ccdn_forum_admin_board_list:
    path: /
    defaults: { _controller: CCDNForumForumBundle:AdminBoard:list }

ccdn_forum_admin_board_create:
    path: /create
    defaults: { _controller: CCDNForumForumBundle:AdminBoard:create }

ccdn_forum_admin_board_create_process:
    path: /create/process
    defaults: { _controller: CCDNForumForumBundle:AdminBoard:createProcess }

ccdn_forum_admin_board_edit:
    path: /edit/{boardId}
    defaults: { _controller: CCDNForumForumBundle:AdminBoard:edit }

ccdn_forum_admin_board_edit_process:
    path: /edit/{boardId}/process
    defaults: { _controller: CCDNForumForumBundle:AdminBoard:editProcess }

ccdn_forum_admin_board_delete:
    path: /delete/{boardId}
    defaults: { _controller: CCDNForumForumBundle:AdminBoard:delete }

ccdn_forum_admin_board_delete_process:
    path: /delete/{boardId}/process
    defaults: { _controller: CCDNForumForumBundle:AdminBoard:deleteProcess }

ccdn_forum_admin_board_reorder_up:
    path: /reorder/{boardId}/up
    defaults: { _controller: CCDNForumForumBundle:AdminBoard:reorder, direction: 0 }

ccdn_forum_admin_board_reorder_down:
    path: /reorder/{boardId}/down
    defaults: { _controller: CCDNForumForumBundle:AdminBoard:reorder, direction: 1 }
