
ccdn_forum_user_subscription_index:
    path: /
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:index, _locale: de }

ccdn_forum_user_subscription_subscribe:
    path: /topic/{topicId}/subscribe
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:subscribe, _locale: de }

ccdn_forum_user_subscription_unsubscribe:
    path: /topic/{topicId}/unsubscribe
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:unsubscribe, _locale: de }
