
ccdn_forum_user_subscription_index:
    pattern: /
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:index, _locale: de }

ccdn_forum_user_subscription_subscribe:
    pattern: /topic/{topicId}/subscribe
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:subscribe, _locale: de }

ccdn_forum_user_subscription_unsubscribe:
    pattern: /topic/{topicId}/unsubscribe
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:unsubscribe, _locale: de }
