
#ccdn_forum_user_category_index:
#    path: /index
#    defaults: { _controller: CCDNForumForumBundle:UserCategory:index, _locale: de, forumName: default }

ccdn_forum_user_category_index:
    path:     /{forumName}
    defaults: { _controller: CCDNForumForumBundle:UserCategory:index, forumName: default }

ccdn_forum_user_category_show:
    path:     /{forumName}/category/{categoryId}
    defaults: { _controller: CCDNForumForumBundle:UserCategory:show, forumName: default }
